STAT_NAMES = {
    "assists": "Assists",
    "bench_points": "Bench Points",
    "biggest_scoring_run": "Biggest Scoring Run",
    "blocks": "Blocks",
    "field_goals_fraction": "Field Goals",
    "field_goal_percentage": "FG%",
    "fouls_personal": "Personal Fouls",
    "fouls_team": "Team Fouls",
    "free_throws_percentage": "FT%",
    "free_throws_fraction": "Free Throws",
    "offensive_rebounds": "Offensive Rebounds",
    "points_fast_break": "Fast Break Points",
    "points_in_the_paint_made": "Points in the Paint",
    "rebounds_total": "Rebounds",
    "steals": "Steals",
    "three_pointers_percentage": "3FG%",
    "three_pointers_fraction": "Three Pointers",
    "time_leading": "Time Leading",
    "turnovers": "Turnovers",
}
